### ISSUE TITLE
Error when starting setup

### ISSUE THREAD

**Issue by Thunderhawk2001** [kc8pnd/VanillaHub#1]
Error when starting setup.exe.

> Folgende Fehler wurden bei diesem Vorgang entdeckt.
	* [29.01.2017 21:27:10] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- Die Datei 'WoWOcto.exe.config' hat einen anderen berechneten Hash, als im Manifest angegeben ist.
		- Quelle: System.Deployment
		- Stapelüberwachung:
			bei System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			bei System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			bei System.Deployment.Application.ComponentVerifier.VerifyComponents()
			bei System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			bei System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			bei System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			bei System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			bei System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

**Comment by Thunderhawk2001** [comment]
Sorry, accidentally hit the close button ^^

**Comment by kc8pnd** [comment]
Be sure that you first have the latest .net framework installed. Then make sure you are downloading all files : https://github.com/kc8pnd/VanillaHub/archive/master.zip and fully extracting before launching setup.exe. Let me know if there are any more errors.

**Comment by Thunderhawk2001** [comment]
Ok. The latest framework (.net 4.6.2 )is installed, I've downloaded all files and extracted them.
After starting setup.exe I receive the error message : "The WoWOcto.exe.config file has a different computed hash than specified in the manifest."

**Comment by Thunderhawk2001** [comment]
With the provided .zip file, the installation works fine, but when I try to install/update a mod, I receive the error message: `The source and destination paths must have identical root directories. It can not be moved across volume.`

![image](https://cloud.githubusercontent.com/assets/14139482/22626128/d0bb860e-eba6-11e6-83cc-b420edc900cb.png)

But the addon folder gets deleted

**Comment by kc8pnd** [comment]
Which add-on have you tried to install. I will try to replucate the problem.

On Feb 5, 2017 8:28 AM, "Thunderhawk2001" <notifications@github.com> wrote:

With the provided .zip file, the installation works fine, but when I try to
install/update a mod, I receive the error message: The source and
destination paths must have identical root directories. It can not be moved
across volume.

[image: image]
<https://cloud.githubusercontent.com/assets/14139482/22626128/d0bb860e-eba6-11e6-83cc-b420edc900cb.png>

But the addon folder gets deleted

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kc8pnd/VanillaHub/issues/1#issuecomment-277516620>, or mute
the thread

**Comment by Thunderhawk2001** [comment]
I've tried to install LunaUnitframes.

kc8pnd <notifications@github.com> schrieb am So., 5. Feb. 2017, 19:16:

**Comment by kc8pnd** [comment]
Hi Thunder, 
Actually studying your error message a bit it looks like a pretty simple issue I may have to look into on my end. 

By any chance are you running your Warcraft folder on a slave drive? You may try moving your Vanilla WoW folder to the same drive as your windows install. It seems that the code that extracts the Temp.zip folder cannot move to a remote disk.

Give that a try,
kc8pnd.

**Comment by Thunderhawk2001** [comment]
I've got WoW Vanilla installed on a small 60gb spare SSD I had lying around.
Will move WoW to the system SSD and try again.

kc8pnd <notifications@github.com> schrieb am Mo., 6. Feb. 2017, 16:09:

**Comment by Thunderhawk2001** [comment]
Sorry, was pretty busy these days.

I've copied WoW to the System SSD and, like you mentioned, VanillaHub works without errors. :)
